/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/roadrunner/roadrunner_ws/src/laser_sub_V6/msg/lasArray.msg
 *
 */


#ifndef LASER_SUB_MESSAGE_LASARRAY_H
#define LASER_SUB_MESSAGE_LASARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <laser_sub/Num.h>

namespace laser_sub
{
template <class ContainerAllocator>
struct lasArray_
{
  typedef lasArray_<ContainerAllocator> Type;

  lasArray_()
    : laserArray()  {
    }
  lasArray_(const ContainerAllocator& _alloc)
    : laserArray(_alloc)  {
    }



   typedef std::vector< ::laser_sub::Num_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::laser_sub::Num_<ContainerAllocator> >::other >  _laserArray_type;
  _laserArray_type laserArray;




  typedef boost::shared_ptr< ::laser_sub::lasArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::laser_sub::lasArray_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct lasArray_

typedef ::laser_sub::lasArray_<std::allocator<void> > lasArray;

typedef boost::shared_ptr< ::laser_sub::lasArray > lasArrayPtr;
typedef boost::shared_ptr< ::laser_sub::lasArray const> lasArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::laser_sub::lasArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::laser_sub::lasArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace laser_sub

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'laser_sub': ['/home/roadrunner/roadrunner_ws/src/laser_sub_V6/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::laser_sub::lasArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::laser_sub::lasArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laser_sub::lasArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laser_sub::lasArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_sub::lasArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_sub::lasArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::laser_sub::lasArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5bd8316bb420e1b5b48d1bf192e5bf85";
  }

  static const char* value(const ::laser_sub::lasArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5bd8316bb420e1b5ULL;
  static const uint64_t static_value2 = 0xb48d1bf192e5bf85ULL;
};

template<class ContainerAllocator>
struct DataType< ::laser_sub::lasArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "laser_sub/lasArray";
  }

  static const char* value(const ::laser_sub::lasArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::laser_sub::lasArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Num[] laserArray\n\
\n\
\n\
================================================================================\n\
MSG: laser_sub/Num\n\
float32 centerX\n\
float32 centerY\n\
float32 radius\n\
";
  }

  static const char* value(const ::laser_sub::lasArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::laser_sub::lasArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.laserArray);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct lasArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::laser_sub::lasArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::laser_sub::lasArray_<ContainerAllocator>& v)
  {
    s << indent << "laserArray[]" << std::endl;
    for (size_t i = 0; i < v.laserArray.size(); ++i)
    {
      s << indent << "  laserArray[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::laser_sub::Num_<ContainerAllocator> >::stream(s, indent + "    ", v.laserArray[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LASER_SUB_MESSAGE_LASARRAY_H
