/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/roadrunner/roadrunner_ws/src/laser_sub_V6/msg/Num.msg
 *
 */


#ifndef LASER_SUB_MESSAGE_NUM_H
#define LASER_SUB_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace laser_sub
{
template <class ContainerAllocator>
struct Num_
{
  typedef Num_<ContainerAllocator> Type;

  Num_()
    : centerX(0.0)
    , centerY(0.0)
    , radius(0.0)  {
    }
  Num_(const ContainerAllocator& _alloc)
    : centerX(0.0)
    , centerY(0.0)
    , radius(0.0)  {
    }



   typedef float _centerX_type;
  _centerX_type centerX;

   typedef float _centerY_type;
  _centerY_type centerY;

   typedef float _radius_type;
  _radius_type radius;




  typedef boost::shared_ptr< ::laser_sub::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::laser_sub::Num_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct Num_

typedef ::laser_sub::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::laser_sub::Num > NumPtr;
typedef boost::shared_ptr< ::laser_sub::Num const> NumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::laser_sub::Num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::laser_sub::Num_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace laser_sub

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'laser_sub': ['/home/roadrunner/roadrunner_ws/src/laser_sub_V6/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::laser_sub::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::laser_sub::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laser_sub::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::laser_sub::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_sub::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::laser_sub::Num_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::laser_sub::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "65790d35a6f6d4aec392918077a52788";
  }

  static const char* value(const ::laser_sub::Num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x65790d35a6f6d4aeULL;
  static const uint64_t static_value2 = 0xc392918077a52788ULL;
};

template<class ContainerAllocator>
struct DataType< ::laser_sub::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "laser_sub/Num";
  }

  static const char* value(const ::laser_sub::Num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::laser_sub::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 centerX\n\
float32 centerY\n\
float32 radius\n\
";
  }

  static const char* value(const ::laser_sub::Num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::laser_sub::Num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.centerX);
      stream.next(m.centerY);
      stream.next(m.radius);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::laser_sub::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::laser_sub::Num_<ContainerAllocator>& v)
  {
    s << indent << "centerX: ";
    Printer<float>::stream(s, indent + "  ", v.centerX);
    s << indent << "centerY: ";
    Printer<float>::stream(s, indent + "  ", v.centerY);
    s << indent << "radius: ";
    Printer<float>::stream(s, indent + "  ", v.radius);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LASER_SUB_MESSAGE_NUM_H
