//*****************************************************************************
//*****************************************************************************
//  FILENAME:  Steer_Pot.h  ( PGA )
//  Version: 3.2, Updated on 2015/3/4 at 22:26:46
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION:  PGA User Module C Language interface file.
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef Steer_Pot_INCLUDE
#define Steer_Pot_INCLUDE

#include <M8C.h>

//-------------------------------------------------
// Constants for Steer_Pot API's.
//-------------------------------------------------
#define Steer_Pot_OFF         0
#define Steer_Pot_LOWPOWER    1
#define Steer_Pot_MEDPOWER    2
#define Steer_Pot_HIGHPOWER   3

#define Steer_Pot_G48_0    0x0C
#define Steer_Pot_G24_0    0x1C

#define Steer_Pot_G16_0    0x08
#define Steer_Pot_G8_00    0x18
#define Steer_Pot_G5_33    0x28
#define Steer_Pot_G4_00    0x38
#define Steer_Pot_G3_20    0x48
#define Steer_Pot_G2_67    0x58
#define Steer_Pot_G2_27    0x68
#define Steer_Pot_G2_00    0x78
#define Steer_Pot_G1_78    0x88
#define Steer_Pot_G1_60    0x98
#define Steer_Pot_G1_46    0xA8
#define Steer_Pot_G1_33    0xB8
#define Steer_Pot_G1_23    0xC8
#define Steer_Pot_G1_14    0xD8
#define Steer_Pot_G1_06    0xE8
#define Steer_Pot_G1_00    0xF8
#define Steer_Pot_G0_93    0xE0
#define Steer_Pot_G0_87    0xD0
#define Steer_Pot_G0_81    0xC0
#define Steer_Pot_G0_75    0xB0
#define Steer_Pot_G0_68    0xA0
#define Steer_Pot_G0_62    0x90
#define Steer_Pot_G0_56    0x80
#define Steer_Pot_G0_50    0x70
#define Steer_Pot_G0_43    0x60
#define Steer_Pot_G0_37    0x50
#define Steer_Pot_G0_31    0x40
#define Steer_Pot_G0_25    0x30
#define Steer_Pot_G0_18    0x20
#define Steer_Pot_G0_12    0x10
#define Steer_Pot_G0_06    0x00

#define Steer_Pot_AGNDBUFAPI 0

#pragma fastcall16 Steer_Pot_Start
#pragma fastcall16 Steer_Pot_SetPower
#pragma fastcall16 Steer_Pot_SetGain
#pragma fastcall16 Steer_Pot_Stop

#if (Steer_Pot_AGNDBUFAPI)
#pragma fastcall16 Steer_Pot_EnableAGNDBuffer
#pragma fastcall16 Steer_Pot_DisableAGNDBuffer
#endif

//-------------------------------------------------
// Prototypes of the Steer_Pot API.
//-------------------------------------------------
extern void Steer_Pot_Start(BYTE bPowerSetting);     // Proxy class 2
extern void Steer_Pot_SetPower(BYTE bPowerSetting);  // Proxy class 2
extern void Steer_Pot_SetGain(BYTE bGainSetting);    // Proxy class 2
extern void Steer_Pot_Stop(void);                    // Proxy class 1

#if (Steer_Pot_AGNDBUFAPI)
extern void Steer_Pot_EnableAGNDBuffer(void);
extern void Steer_Pot_DisableAGNDBuffer(void);
#endif

//-------------------------------------------------
// Register Addresses for Steer_Pot
//-------------------------------------------------

#pragma ioport  Steer_Pot_GAIN_CR0: 0x071
BYTE            Steer_Pot_GAIN_CR0;
#pragma ioport  Steer_Pot_GAIN_CR1: 0x072
BYTE            Steer_Pot_GAIN_CR1;
#pragma ioport  Steer_Pot_GAIN_CR2: 0x073
BYTE            Steer_Pot_GAIN_CR2;
#pragma ioport  Steer_Pot_GAIN_CR3: 0x070
BYTE            Steer_Pot_GAIN_CR3;

#endif
// end of file Steer_Pot.h
